version: "3.7"
services:
  app:
    build:
      args:
        user: CodewithRSK
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: todo
    container_name: todo-application
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - todo-database
    links:
      - todo-database
    networks:
      - todo-network
  nginx:
    image: nginx:alpine
    container_name: todo-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d/
    networks:
      - todo-network
    depends_on:
      - todo-database
      - phpmyadmin
  todo-database:
    image: mysql:5.7
    container_name: todo-database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - todo-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: todo-phpmyadmin
    restart: unless-stopped
    tty: true
    depends_on:
      - todo-database
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: todo-database
      PMA_PORT: 3306
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 2048M
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
